on: 
  push:
  pull_request:
  schedule:
  - cron: '0 19 * * *'
name: Build and Test
jobs:
  test:
    strategy:
      matrix:
        go-version: [1.15, 1.15.1, 1.15.2]
        platform: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.platform }}
    steps:
    - name: Install Go
      uses: actions/setup-go@v2
      with:
        go-version: ${{ matrix.go-version }}
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Build Code
      run: go build cmd/jobs.go
    - name: Test
      run: go test ./... -v
  run:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'
    steps:
    - name: Install Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.15
    - name: "Checkout code"
      uses: actions/checkout@v2
    - name: Run Program
      run: go run cmd/jobs.go
    - name: Upload CSV
      uses: actions/upload-artifact@v2
      with:
        path: '*.csv'
        if-no-files-found: error 